name: Mi workflow

on: push

jobs:
  tareas:
   runs-on: ubuntu-latest
   steps:
    - name: Bajar codigo
      uses: actions/checkout@v4
      
    - name: Instalar paquete
      run: pip install pytest

    - name: Utilizar test
      run: pytest test.py
